// This file was auto-generated by Fern from our API Definition.

import * as core from "../../core/index.js";
import * as errors from "../../errors/index.js";
import * as CloudflareApi from "../index.js";

export class RequestTimeoutError extends errors.CloudflareApiError {
    declare public readonly body: CloudflareApi.AiAuditApiResponseCommonFailure;

    constructor(body: CloudflareApi.AiAuditApiResponseCommonFailure, rawResponse?: core.RawResponse) {
        super({
            message: "RequestTimeoutError",
            statusCode: 408,
            body: body,
            rawResponse: rawResponse,
        });
        Object.setPrototypeOf(this, new.target.prototype);
        if (Error.captureStackTrace) {
            Error.captureStackTrace(this, this.constructor);
        }

        this.name = "RequestTimeoutError";
    }
}
