// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         account_id: "account_id",
 *         rule_id: "rule_id"
 *     }
 */
export interface DeleteRulesRequest {
    /** The ID of the account. */
    account_id: string;
    /** The UUID of the TCP Flow Protection rule to delete. */
    rule_id: string;
}
