// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../../../../index.js";

/**
 * @example
 *     {
 *         zone_id: "zone_id",
 *         body: {
 *             username_expressions: []
 *         }
 *     }
 *
 * @example
 *     {
 *         zone_id: "zone_id",
 *         body: {
 *             authentication_settings: {
 *                 failure_criteria: {
 *                     kind: "status_code",
 *                     status_codes: [401, 403]
 *                 },
 *                 success_criteria: {
 *                     kind: "status_code",
 *                     status_codes: [200, 201]
 *                 }
 *             }
 *         }
 *     }
 *
 * @example
 *     {
 *         zone_id: "zone_id",
 *         body: {
 *             user_profiles: "enabled",
 *             username_expressions: ["http.request.body.form[\"username\"][0]", "lookup_json_string(http.request.body.raw, \"username\")"]
 *         }
 *     }
 *
 * @example
 *     {
 *         zone_id: "zone_id",
 *         body: {
 *             authentication_settings: {
 *                 success_criteria: {
 *                     kind: "status_code",
 *                     status_codes: [200]
 *                 }
 *             }
 *         }
 *     }
 */
export interface UpdateFraudRequest {
    /** Identifier. */
    zone_id: string;
    body: CloudflareApi.FraudFraudSettings;
}
