// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { normalizeClientOptionsWithAuth, type NormalizedClientOptionsWithAuth } from "../../../../BaseClient.js";
import * as core from "../../../../core/index.js";
import { mergeHeaders } from "../../../../core/headers.js";
import { mergeAdditionalBodyParameters } from "../../../../core/requestBody.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import type * as CloudflareApi from "../../../index.js";
import { OriginCloudRegionsClient } from "../resources/originCloudRegions/client/Client.js";
import { SettingsClient } from "../resources/settings/client/Client.js";

export declare namespace CacheClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class CacheClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<CacheClient.Options>;
    protected _originCloudRegions: OriginCloudRegionsClient | undefined;
    protected _settings: SettingsClient | undefined;

    constructor(options: CacheClient.Options = {}) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    public get originCloudRegions(): OriginCloudRegionsClient {
        return (this._originCloudRegions ??= new OriginCloudRegionsClient(this._options));
    }

    public get settings(): SettingsClient {
        return (this._settings ??= new SettingsClient(this._options));
    }

    /**
     * Marks cached content as stale for one environment of the zone. Content cached for the zone's other environments, including production, is not affected. Otherwise this works like `POST /zones/{zone_id}/invalidate_cache`: the next request for invalidated content makes Cloudflare revalidate it with your origin, and the request body takes the same fields.
     *
     * Environments are part of [Version Management](https://developers.cloudflare.com/version-management/). To delete the content instead, use `POST /zones/{zone_id}/environments/{environment_id}/purge_cache`.
     *
     * Invalidating by URL (`files`) does not work for environments that select requests by IP address, country, ASN, or threat score, and fails with error `1136`. Use `tags`, `hosts`, `prefixes`, or `purge_everything` for those environments.
     *
     * ### Availability and limits
     *
     * Rate limits and the number of items you can send in one request depend on your plan. See [Purge cache: availability and limits](https://developers.cloudflare.com/cache/how-to/purge-cache/#availability-and-limits).
     *
     * @param {CloudflareApi.InvalidateEnvironmentCacheRequest} request
     * @param {CacheClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link errors.CloudflareApiError}
     * @throws {@link errors.CloudflareApiTimeoutError}
     *
     * @example
     *     await client.cache.invalidateEnvironment({
     *         zone_id: "zone_id",
     *         environment_id: "environment_id",
     *         body: {
     *             tags: ["product-1234", "homepage"]
     *         }
     *     })
     *
     * @example
     *     await client.cache.invalidateEnvironment({
     *         zone_id: "zone_id",
     *         environment_id: "environment_id",
     *         body: {
     *             purge_everything: true
     *         }
     *     })
     *
     * @example
     *     await client.cache.invalidateEnvironment({
     *         zone_id: "zone_id",
     *         environment_id: "environment_id",
     *         body: {
     *             hosts: ["www.example.com", "images.example.com"]
     *         }
     *     })
     *
     * @example
     *     await client.cache.invalidateEnvironment({
     *         zone_id: "zone_id",
     *         environment_id: "environment_id",
     *         body: {
     *             prefixes: ["www.example.com/blog/", "images.example.com/avatars/"]
     *         }
     *     })
     *
     * @example
     *     await client.cache.invalidateEnvironment({
     *         zone_id: "zone_id",
     *         environment_id: "environment_id",
     *         body: {
     *             files: ["https://www.example.com/css/styles.css", "https://www.example.com/js/index.js"]
     *         }
     *     })
     *
     * @example
     *     await client.cache.invalidateEnvironment({
     *         zone_id: "zone_id",
     *         environment_id: "environment_id",
     *         body: {
     *             files: [{
     *                     headers: {
     *                         "Accept-Language": "zh-CN",
     *                         "CF-Device-Type": "desktop",
     *                         "CF-IPCountry": "US"
     *                     },
     *                     url: "https://www.example.com/cat_picture.jpg"
     *                 }, {
     *                     headers: {
     *                         "Accept-Language": "en-US",
     *                         "CF-Device-Type": "mobile",
     *                         "CF-IPCountry": "DE"
     *                     },
     *                     url: "https://www.example.com/dog_picture.jpg"
     *                 }]
     *         }
     *     })
     */
    public invalidateEnvironment(
        request: CloudflareApi.InvalidateEnvironmentCacheRequest,
        requestOptions?: CacheClient.RequestOptions,
    ): core.HttpResponsePromise<CloudflareApi.CachePurgeApiResponseSingleIdResult | null> {
        return core.HttpResponsePromise.fromPromise(this.__invalidateEnvironment(request, requestOptions));
    }

    private async __invalidateEnvironment(
        request: CloudflareApi.InvalidateEnvironmentCacheRequest,
        requestOptions?: CacheClient.RequestOptions,
    ): Promise<core.WithRawResponse<CloudflareApi.CachePurgeApiResponseSingleIdResult | null>> {
        const { zone_id: zoneId, environment_id: environmentId, body: _body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.CloudflareApiEnvironment.Default,
                `zones/${core.url.encodePathParam(zoneId)}/environments/${core.url.encodePathParam(environmentId)}/invalidate_cache`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(_body, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as CloudflareApi.CachePurgeApiResponseSingleIdResult | null,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.CloudflareApiError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/zones/{zone_id}/environments/{environment_id}/invalidate_cache",
        );
    }

    /**
     * Deletes cached content for one environment of the zone. Content cached for the zone's other environments, including production, is not affected. Otherwise this works like `POST /zones/{zone_id}/purge_cache`: the next request for purged content is a cache `MISS`, and the request body takes the same fields.
     *
     * Environments are part of [Version Management](https://developers.cloudflare.com/version-management/). To keep content cached and have Cloudflare revalidate it instead, use `POST /zones/{zone_id}/environments/{environment_id}/invalidate_cache`.
     *
     * Purging by URL (`files`) does not work for environments that select requests by IP address, country, ASN, or threat score, and fails with error `1136`. Use `tags`, `hosts`, `prefixes`, or `purge_everything` for those environments.
     *
     * ### Availability and limits
     *
     * Rate limits and the number of items you can send in one request depend on your plan. See [Purge cache: availability and limits](https://developers.cloudflare.com/cache/how-to/purge-cache/#availability-and-limits).
     *
     * @param {CloudflareApi.PurgeEnvironmentCacheRequest} request
     * @param {CacheClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link errors.CloudflareApiError}
     * @throws {@link errors.CloudflareApiTimeoutError}
     *
     * @example
     *     await client.cache.purgeEnvironment({
     *         zone_id: "zone_id",
     *         environment_id: "environment_id",
     *         body: {
     *             tags: ["product-1234", "homepage"]
     *         }
     *     })
     *
     * @example
     *     await client.cache.purgeEnvironment({
     *         zone_id: "zone_id",
     *         environment_id: "environment_id",
     *         body: {
     *             purge_everything: true
     *         }
     *     })
     *
     * @example
     *     await client.cache.purgeEnvironment({
     *         zone_id: "zone_id",
     *         environment_id: "environment_id",
     *         body: {
     *             hosts: ["www.example.com", "images.example.com"]
     *         }
     *     })
     *
     * @example
     *     await client.cache.purgeEnvironment({
     *         zone_id: "zone_id",
     *         environment_id: "environment_id",
     *         body: {
     *             prefixes: ["www.example.com/blog/", "images.example.com/avatars/"]
     *         }
     *     })
     *
     * @example
     *     await client.cache.purgeEnvironment({
     *         zone_id: "zone_id",
     *         environment_id: "environment_id",
     *         body: {
     *             files: ["https://www.example.com/css/styles.css", "https://www.example.com/js/index.js"]
     *         }
     *     })
     *
     * @example
     *     await client.cache.purgeEnvironment({
     *         zone_id: "zone_id",
     *         environment_id: "environment_id",
     *         body: {
     *             files: [{
     *                     headers: {
     *                         "Accept-Language": "zh-CN",
     *                         "CF-Device-Type": "desktop",
     *                         "CF-IPCountry": "US"
     *                     },
     *                     url: "https://www.example.com/cat_picture.jpg"
     *                 }, {
     *                     headers: {
     *                         "Accept-Language": "en-US",
     *                         "CF-Device-Type": "mobile",
     *                         "CF-IPCountry": "DE"
     *                     },
     *                     url: "https://www.example.com/dog_picture.jpg"
     *                 }]
     *         }
     *     })
     */
    public purgeEnvironment(
        request: CloudflareApi.PurgeEnvironmentCacheRequest,
        requestOptions?: CacheClient.RequestOptions,
    ): core.HttpResponsePromise<CloudflareApi.CachePurgeApiResponseSingleIdResult | null> {
        return core.HttpResponsePromise.fromPromise(this.__purgeEnvironment(request, requestOptions));
    }

    private async __purgeEnvironment(
        request: CloudflareApi.PurgeEnvironmentCacheRequest,
        requestOptions?: CacheClient.RequestOptions,
    ): Promise<core.WithRawResponse<CloudflareApi.CachePurgeApiResponseSingleIdResult | null>> {
        const { zone_id: zoneId, environment_id: environmentId, body: _body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.CloudflareApiEnvironment.Default,
                `zones/${core.url.encodePathParam(zoneId)}/environments/${core.url.encodePathParam(environmentId)}/purge_cache`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(_body, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as CloudflareApi.CachePurgeApiResponseSingleIdResult | null,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.CloudflareApiError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/zones/{zone_id}/environments/{environment_id}/purge_cache",
        );
    }

    /**
     * Marks cached content as stale in every Cloudflare data center and cache tier, including Cache Reserve. The content stays in cache. The next request for it makes Cloudflare revalidate it with your origin, using the `ETag` and `Last-Modified` values it was cached with:
     *
     * - If your origin answers `304 Not Modified`, Cloudflare serves the cached copy without downloading it again, and `CF-Cache-Status` is `REVALIDATED`.
     * - If your origin sends a full response, Cloudflare serves and caches the new content, and `CF-Cache-Status` is `EXPIRED`.
     *
     * With Tiered Cache, each tier revalidates with the tier above it, so a visitor can see `EXPIRED` even when your origin answered `304`.
     *
     * Until content is revalidated, your `stale-while-revalidate` and `stale-if-error` directives still apply, counted from the time you invalidated it. For example, if your origin fails during revalidation, Cloudflare can keep serving the stale copy for the `stale-if-error` window.
     *
     * ### Invalidate or purge?
     *
     * - **Invalidate** when content may not have changed, for example after a deploy. Unchanged content costs your origin a `304` instead of a full response. That saving needs an origin that sends `ETag` or `Last-Modified` and answers conditional requests. Otherwise, every revalidation downloads the full response.
     * - **Purge**, with `POST /zones/{zone_id}/purge_cache`, when content must not be served again, for example content you removed for legal or security reasons.
     *
     * Invalidating takes the same request bodies as purging, needs the same permission, and counts against the same rate limits. After a broad invalidation, such as `purge_everything`, expect more conditional requests to your origin while visitors request the invalidated content again.
     *
     * ### Choose what to invalidate
     *
     * Send one of these fields in the request body:
     *
     * - `files`: specific URLs. If your cache key includes request headers, send each URL with the header values it was cached with.
     * - `tags`: all content whose `Cache-Tag` response header contains one of the tags.
     * - `hosts`: all content cached for the hostnames.
     * - `prefixes`: all content whose URL starts with one of the prefixes.
     * - `purge_everything`: all cached content in the zone.
     *
     * ### Check the result
     *
     * A `200` response with `success: true` means Cloudflare accepted the request. To check, request an invalidated URL and confirm that the `CF-Cache-Status` response header is `REVALIDATED` or `EXPIRED`.
     *
     * ### Availability and limits
     *
     * Rate limits and the number of items you can send in one request depend on your plan. See [Purge cache: availability and limits](https://developers.cloudflare.com/cache/how-to/purge-cache/#availability-and-limits).
     *
     * @param {CloudflareApi.InvalidateCacheRequest} request
     * @param {CacheClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link errors.CloudflareApiError}
     * @throws {@link errors.CloudflareApiTimeoutError}
     *
     * @example
     *     await client.cache.invalidate({
     *         zone_id: "zone_id",
     *         body: {
     *             tags: ["product-1234", "homepage"]
     *         }
     *     })
     *
     * @example
     *     await client.cache.invalidate({
     *         zone_id: "zone_id",
     *         body: {
     *             purge_everything: true
     *         }
     *     })
     *
     * @example
     *     await client.cache.invalidate({
     *         zone_id: "zone_id",
     *         body: {
     *             hosts: ["www.example.com", "images.example.com"]
     *         }
     *     })
     *
     * @example
     *     await client.cache.invalidate({
     *         zone_id: "zone_id",
     *         body: {
     *             prefixes: ["www.example.com/blog/", "images.example.com/avatars/"]
     *         }
     *     })
     *
     * @example
     *     await client.cache.invalidate({
     *         zone_id: "zone_id",
     *         body: {
     *             files: ["https://www.example.com/css/styles.css", "https://www.example.com/js/index.js"]
     *         }
     *     })
     *
     * @example
     *     await client.cache.invalidate({
     *         zone_id: "zone_id",
     *         body: {
     *             files: [{
     *                     headers: {
     *                         "Accept-Language": "zh-CN",
     *                         "CF-Device-Type": "desktop",
     *                         "CF-IPCountry": "US"
     *                     },
     *                     url: "https://www.example.com/cat_picture.jpg"
     *                 }, {
     *                     headers: {
     *                         "Accept-Language": "en-US",
     *                         "CF-Device-Type": "mobile",
     *                         "CF-IPCountry": "DE"
     *                     },
     *                     url: "https://www.example.com/dog_picture.jpg"
     *                 }]
     *         }
     *     })
     */
    public invalidate(
        request: CloudflareApi.InvalidateCacheRequest,
        requestOptions?: CacheClient.RequestOptions,
    ): core.HttpResponsePromise<CloudflareApi.CachePurgeApiResponseSingleIdResult | null> {
        return core.HttpResponsePromise.fromPromise(this.__invalidate(request, requestOptions));
    }

    private async __invalidate(
        request: CloudflareApi.InvalidateCacheRequest,
        requestOptions?: CacheClient.RequestOptions,
    ): Promise<core.WithRawResponse<CloudflareApi.CachePurgeApiResponseSingleIdResult | null>> {
        const { zone_id: zoneId, body: _body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.CloudflareApiEnvironment.Default,
                `zones/${core.url.encodePathParam(zoneId)}/invalidate_cache`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(_body, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as CloudflareApi.CachePurgeApiResponseSingleIdResult | null,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.CloudflareApiError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/zones/{zone_id}/invalidate_cache",
        );
    }

    /**
     * Deletes cached content in every Cloudflare data center and cache tier, including Cache Reserve. The next request for purged content is a cache `MISS`: Cloudflare fetches the full response from your origin and caches it again. Cloudflare does not serve purged content from cache again, even if your origin is unavailable.
     *
     * To keep content cached and have Cloudflare revalidate it with your origin instead, use `POST /zones/{zone_id}/invalidate_cache`.
     *
     * ### Choose what to purge
     *
     * Send one of these fields in the request body:
     *
     * - `files`: specific URLs. If your cache key includes request headers, send each URL with the header values it was cached with.
     * - `tags`: all content whose `Cache-Tag` response header contains one of the tags.
     * - `hosts`: all content cached for the hostnames.
     * - `prefixes`: all content whose URL starts with one of the prefixes.
     * - `purge_everything`: all cached content in the zone.
     *
     * ### Check the result
     *
     * A `200` response with `success: true` means Cloudflare accepted the request. It does not confirm that any content was cached or removed. To check, request a purged URL and confirm that the `CF-Cache-Status` response header is `MISS`.
     *
     * ### Availability and limits
     *
     * Rate limits and the number of items you can send in one request depend on your plan. See [Purge cache: availability and limits](https://developers.cloudflare.com/cache/how-to/purge-cache/#availability-and-limits).
     *
     * @param {CloudflareApi.PurgeCacheRequest} request
     * @param {CacheClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link errors.CloudflareApiError}
     * @throws {@link errors.CloudflareApiTimeoutError}
     *
     * @example
     *     await client.cache.purge({
     *         zone_id: "zone_id",
     *         body: {
     *             tags: ["product-1234", "homepage"]
     *         }
     *     })
     *
     * @example
     *     await client.cache.purge({
     *         zone_id: "zone_id",
     *         body: {
     *             purge_everything: true
     *         }
     *     })
     *
     * @example
     *     await client.cache.purge({
     *         zone_id: "zone_id",
     *         body: {
     *             hosts: ["www.example.com", "images.example.com"]
     *         }
     *     })
     *
     * @example
     *     await client.cache.purge({
     *         zone_id: "zone_id",
     *         body: {
     *             prefixes: ["www.example.com/blog/", "images.example.com/avatars/"]
     *         }
     *     })
     *
     * @example
     *     await client.cache.purge({
     *         zone_id: "zone_id",
     *         body: {
     *             files: ["https://www.example.com/css/styles.css", "https://www.example.com/js/index.js"]
     *         }
     *     })
     *
     * @example
     *     await client.cache.purge({
     *         zone_id: "zone_id",
     *         body: {
     *             files: [{
     *                     headers: {
     *                         "Accept-Language": "zh-CN",
     *                         "CF-Device-Type": "desktop",
     *                         "CF-IPCountry": "US"
     *                     },
     *                     url: "https://www.example.com/cat_picture.jpg"
     *                 }, {
     *                     headers: {
     *                         "Accept-Language": "en-US",
     *                         "CF-Device-Type": "mobile",
     *                         "CF-IPCountry": "DE"
     *                     },
     *                     url: "https://www.example.com/dog_picture.jpg"
     *                 }]
     *         }
     *     })
     */
    public purge(
        request: CloudflareApi.PurgeCacheRequest,
        requestOptions?: CacheClient.RequestOptions,
    ): core.HttpResponsePromise<CloudflareApi.CachePurgeApiResponseSingleIdResult | null> {
        return core.HttpResponsePromise.fromPromise(this.__purge(request, requestOptions));
    }

    private async __purge(
        request: CloudflareApi.PurgeCacheRequest,
        requestOptions?: CacheClient.RequestOptions,
    ): Promise<core.WithRawResponse<CloudflareApi.CachePurgeApiResponseSingleIdResult | null>> {
        const { zone_id: zoneId, body: _body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.CloudflareApiEnvironment.Default,
                `zones/${core.url.encodePathParam(zoneId)}/purge_cache`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(_body, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as CloudflareApi.CachePurgeApiResponseSingleIdResult | null,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.CloudflareApiError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/zones/{zone_id}/purge_cache");
    }
}
